TrainWeb/Models/Article.cs
namespace TrainWeb.Models
{
    public class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }

        public Article(long id, string title, string description, string image)
        {
            Id = id;
            Title = title;
            Description = description;
            Image = image;
        }
    }
}

TrainWeb/Models/Contact.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TrainWeb.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [MinLength(3, ErrorMessage = "حداقل طول نام، 3 کاراکتر است")]
        [MaxLength(100, ErrorMessage = "حداکثر طول نام، 100 کاراکتر است")]
        public string Name { get; set; }

        [Required(ErrorMessage = "این فیلد اجباری است")]
        [EmailAddress(ErrorMessage = "مقدار وارد شده ایمیل صحیح نیست")]
        public string Email { get; set; }

        public int Service { get; set; }
        public string Message { get; set; }
        public SelectList Services { get; set; }
    }
}

TrainWeb/Models/ErrorViewModel.cs
using System;

namespace TrainWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TrainWeb/Models/Project.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace TrainWeb.Models
{
	public class Project
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Client { get; set; }
		public string Description { get; set; }
		public string Image { get; set; }
		public DateTime CreateDateTime { get; set; }
		public DateTime UpdateDateTime { get; set; }

		public Project(int id, string name, string client, string description, string image)
		{
			Id = id;
			Name = name;
			Client = client;
			Description = description;
			Image = image;
		}
		public Project(int id, string name, string client, string description, string image, DateTime createDateTime, DateTime updateDateTime)
		{
			Id = id;
			Name = name;
			Client = client;
			Description = description;
			Image = image;
			CreateDateTime = createDateTime;
			UpdateDateTime = updateDateTime;
		}
	}
}

TrainWeb/Models/Service.cs
namespace TrainWeb.Models
{
    public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Service(int id, string name)
        {
            Id = id;
            Name = name;
        }
    }
}

TrainWeb/Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using TrainWeb.Models;

namespace TrainWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly List<Service> _services = new List<Service>
        {
            new Service(1, "نقره ای"),
            new Service(2, "طلایی"),
            new Service(3, "پلاتین"),
            new Service(4, "الماس"),
        };
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            var model = new Contact
            {
                Services = new SelectList(_services, "Id", "Name")
            };
            return View(model);
        }

        public IActionResult ProjectDetait(int id)
        {
            var project = ProjectData.ProjectsData.GetProject(id);
            return View(project);
        }

        public IActionResult ArticleDetait(int id)
        {
            var articel = ArticleData.ArticlesData.GetArticle(id);
            return View(articel);
        }

        [HttpPost]
        public IActionResult Contact(Contact model)
        {
            model.Services = new SelectList(_services, "Id", "Name");
            if (!ModelState.IsValid)
            {
                ViewBag.error = "ارسال فرم با خطا مواجه شد. لطفا مجددا تلاش فرمایید.";
                return View(model);
            }

            ModelState.Clear();
            model = new Contact
            {
                Services = new SelectList(_services, "Id", "Name")
            };
            ViewBag.success = "ارسال فرم با موفقیت انجام شد!";
	        return View(model);
        }
	}
}

TrainWeb/ViewComponents/ArticlesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using TrainWeb.Models;

namespace TrainWeb.ViewComponents
{
	public class ArticlesViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View("_Articles", ArticleData.ArticlesData.GetAllArticle());
		}
	}
}

TrainWeb/ViewComponents/ProjectsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using TrainWeb.Models;

namespace TrainWeb.ViewComponents
{
	public class ProjectsViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View("_Projects", ProjectData.ProjectsData.GetAllProject());
		}
	}
}

TrainWeb/Views/Home/ArticleDetait.cshtml
@model Article
@{
    ViewData["Title"] = "Contact Page";
}
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.Id</td>
                    <td><img width="75" src="~/assets/images/blog/@Model.Image" /></td>
                    <td>@Model.Title</td>
                    <td>@Model.Description</td>
                </tr>
            </tbody>
        </table>
    </div>
</section>

TrainWeb/Views/Home/Components/Articles/_Articles.cshtml
@model IEnumerable<Article>

<section class="latest-blog-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
		<div class="row">
			@foreach (var artic in Model)
			{
			    <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="~/assets/images/blog/@artic.Image" alt="@artic.Title">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" asp-controller="Home" asp-action="ArticleDetait" asp-route-id="@artic.Id">
                                    @artic.Title
                                </a>
                            </h5>
                            <p class="card-text">
                                @artic.Description
                            </p>
                            <p class="mb-0"><a class="more-link" asp-controller="Home" asp-action="ArticleDetait" asp-route-id="@artic.Id">ادامه مطلب</a></p>
                        </div>
                    </div>
                </div>
			}
		</div>
	</div>
</section>

TrainWeb/Views/Home/Components/Projects/_Projects.cshtml
@model IEnumerable<Project>

<section class="featured-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
        <div class="row">
            @foreach (var proj in Model)
            {
                <div class="col-md-6 mb-5">
                    <div class="card project-card">
                        <div class="row no-gutters">
                            <div class="col-lg-4 card-img-holder">
                                <img src="~/assets/images/project/@proj.Image" class="card-img" alt="@proj.Name">
                            </div>
                            <div class="col-lg-8">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a asp-controller="Home" asp-action="ProjectDetait" asp-route-id="@proj.Id" class="theme-link">
                                            @proj.Name
                                        </a>
                                    </h5>
                                    <p class="card-text">
                                        @proj.Description
                                    </p>
                                    <p class="card-text"><small class="text-muted">Client: @proj.Client</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
	</div>
</section>

TrainWeb/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "Contact Page";
}
<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
        <h2 class="heading">ارتباط با ما</h2>
        <div class="intro">
            <p>
                شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                نوشته و ارسال کنید
            </p>
            <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item mb-3">
                    <a class="twitter" href="#">
                        <i class="fab fa-twitter fa-fw fa-lg"></i>
                    </a>
                </li>

                <li class="list-inline-item mb-3">
                    <a class="linkedin" href="#">
                        <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="github" href="#">
                        <i class="fab fa-github-alt fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="instagram" href="#">
                        <i class="fab fa-instagram fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="stack-overflow" href="#">
                        <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="medium" href="#">
                        <i class="fab fa-medium-m fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="codepen" href="#">
                        <i class="fab fa-codepen fa-fw fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-controller="Home" asp-action="Contact">
            @if (!string.IsNullOrWhiteSpace(ViewBag.error))
            {
                <div class="alert-danger">@ViewBag.error</div>

            }
            else if (!string.IsNullOrWhiteSpace(ViewBag.success))
            {
                <div class="alert-success">@ViewBag.success</div>
            }
            <h3 class="text-center mb-3">در دسترس باشید!</h3>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="نام">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <select class="custom-select" asp-for="Service" asp-items="Model.Services">
                        <option selected>سرویس مورد نظر خود را انتخاب کنید...</option>
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="sr-only" asp-for="Message">پیغام شما</label>
                    <textarea class="form-control" asp-for="Message" placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                </div>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                </div>
            </div>
        </form>
    </div>
</section>

TrainWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section class="about-me-section p-3 p-lg-5 theme-bg-light">
	<div class="container">
		<div class="profile-teaser media flex-column flex-lg-row">
			<img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="~/assets/images/me.jpeg" alt="">
			<div class="media-body">
				<h2 class="name font-weight-bold mb-1">Hamid1021</h2>
				<div class="tagline mb-3">برنامه نویس</div>
				<div class="bio mb-4">
					لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
					طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
					جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
				</div>
				<div class="mb-4">
					<a class="btn btn-secondary mb-3" href="#">
						<i class="fas fa-file-alt ml-2"></i>
						<span class="d-none d-md-inline">مشاهده </span> نمونه کارها
					</a>
				</div>
			</div>

		</div>
	</div>
</section>

@await Component.InvokeAsync("Projects")

<div class="container">
	<hr>
</div>

@await Component.InvokeAsync("Articles")

TrainWeb/Views/Home/ProjectDetait.cshtml
@model Project
@{
    ViewData["Title"] = $"{Model.Name}";
}

<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Client</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.Id</td>
                    <td><img width="75" src="~/assets/images/project/@Model.Image" /></td>
                    <td>@Model.Name</td>
                    <td>@Model.Client</td>
                    <td>@Model.Description</td>
                </tr>
            </tbody>
        </table>
    </div>
</section>

TrainWeb/Views/Shared/_Header.cshtml
<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">Hamid1021</a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/assets/images/me.jpeg" alt="image">

                    <div class="bio mb-3">
                        Hey! Im New Developer. Hello World!
                    </div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی<span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">
                            <i class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با ما
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

TrainWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <title>Train Template | @ViewData["Title"]</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="~/favicon.ico">

    <script defer src="~/assets/fontawesome/js/all.js"></script>
    <link rel="stylesheet" href="~/assets/css/theme-1.css">
    <link rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>
    <partial name="_Header.cshtml" />
    <div class="main-wrapper">
        @RenderBody()
        <footer class="footer text-center py-4">
            <small class="copyright">
                CopyRight
            </small>
        </footer>

    </div>

    <!-- Javascript -->
    <script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
    <script src="~/assets/plugins/popper.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>

</html>